title: Voeg een knop toe met een OnClick methode
hero_image: images/banner.png
description: Voeg een knop toe en voeg een OnClick methode toe die wordt aangeroepen wanneer op de knop wordt geklikt
version: 4
listed: false
copyedit: false
last_tested: "2021-11-18"
steps:
  - 
    title: Voeg een knop toe met een OnClick methode

